
author: Jian Wang
title: Jian Wang | 王坚

permalink: /:year/:month/:day/:title/
url: https://elan2wang.github.io/note

paginate: 20
safe: true
lsi: false
highlighter: rouge

google_analytics_tracking_id: UA-46598958-1
