
author: Jian Wang
title: Jian Wang | 王坚

permalink: /:year/:month/:day/:title/
url: http://elan2wang.github.io/note

paginate: 15
safe: true
lsi: false
pygments: true
markdown: rdiscount

google_analytics_tracking_id: UA-46598958-1
